source "https://api.berkshelf.com"

cookbook "apt"
cookbook "phpenv", path: "./site-cookbooks/phpenv"
cookbook "hostsfile"
cookbook "ruby-ng"
cookbook "capistrano", path: "./site-cookbooks/capistrano"