# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.cache.scope = :box
  config.vbguest.auto_update = true
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 1024]
  end

  config.vm.define :develop do |develop|
    develop.omnibus.chef_version = :latest
    develop.vm.hostname = "develop"
    develop.vm.box = "bento/ubuntu-14.04"
    develop.vm.network :private_network, ip: "192.168.33.10"

    develop.vm.synced_folder "application", "/var/www/application/current",
    id: "vagrant-root", :nfs => false,
    :owner => "vagrant",
    :group => "www-data",
    :mount_options => ["dmode=775,fmode=755"]

    develop.vm.provision :chef_solo do |chef|
      chef.channel = "stable"
      chef.version = "12.10.24"
      chef.log_level = "warn"
      chef.cookbooks_path = "./cookbooks"
      chef.json = {
        nginx: {
          docroot: {
            owner: "vagrant",
            group: "vagrant",
            path: "/var/www/application/current/app/webroot",
            force_create: true
          },
          default: {
            fastcgi_params: { CAKE_ENV: "development" }
          },
          test: {
            available: true,
            fastcgi_params: { CAKE_ENV: "test" }
          }
        }
      }
      chef.run_list = %w[ 
        recipe[apt]
        recipe[phpenv::default]
        recipe[phpenv::composer]
        recipe[phpenv::develop]
        recipe[ruby-ng]
        recipe[capistrano]
      ]
    end
  end

  config.vm.define :ci do |ci|
    ci.omnibus.chef_version = :latest
    ci.vm.hostname = "ci"
    ci.vm.box = "bento/ubuntu-14.04"
    ci.vm.network :private_network, ip: "192.168.33.100"

    ci.vm.provision :chef_solo do |chef|
      chef.channel = "stable"
      chef.version = "12.10.24"
      chef.log_level = "warn"
      chef.cookbooks_path = "./cookbooks"
      chef.json = {
        nginx: {
          docroot: {
            path: "/var/lib/jenkins/jobs/blogapp/workspace/app/webroot",
          },
          default: {
            fastcgi_params: { CAKE_ENV: "development" }
          },
          test: {
            available: true,
            fastcgi_params: { CAKE_ENV: "ci" }
          }
        }
      }
      chef.run_list = %w[
        recipe[apt]
        recipe[phpenv::default]
        recipe[phpenv::composer]
        recipe[phpenv::develop]
        recipe[ruby-ng]
        recipe[capistrano]
        recipe[apt-jenkins]
      ]
    end
  end

  config.vm.define :deploy do |deploy|
    deploy.omnibus.chef_version = :latest
    deploy.vm.hostname = "deploy"
    deploy.vm.box = "bento/ubuntu-14.04"
    deploy.vm.network :private_network, ip: "192.168.33.200"

    deploy.vm.provision :chef_solo do |chef|
      chef.channel = "stable"
      chef.version = "12.10.24"
      chef.log_level = "warn"
      chef.cookbooks_path = "./cookbooks"
      chef.json = {
        nginx: {
          docroot: {
            owner: "vagrant",
            group: "vagrant",
            path: "/var/www/application/current/app/webroot",
            force_create: true
          },
          default: {
            fastcgi_params: { CAKE_ENV: "development" }
          },
        }
      }
      chef.run_list = %w[ 
        recipe[apt]
        recipe[phpenv::default]
        recipe[phpenv::composer]
      ]
    end
  end
end
